# Start of your personal configuration.yaml file
# This file is an example!
# Read it, understand it and copy it! :D

# Your hacs token for using HACS
# hacs:
#   token: paste-token-here


# Camera example
# camera:
#   - platform: generic
#     name: Garage camera
#     stream_source: "rtsp://192.168.1.1:554/h264?username=admin&password=admin"
#     still_image_url: "http://192.168.1.1/cgi-bin/snapshot.cgi?stream=0"


# Tado (user and pass stored in secrets.yaml)
# tado:
#   username: !secret tado_username
#   password: !secret tado_password


# Vacuum example
# vacuum:
#   - platform: xiaomi_miio
#     name: Consuela
#     host: 192.168.1.2
#     token: vacuum-token-here

# The below things DON'T WORK if you place this file in PACKAGES folder!!!!!!!!!!!
# Only use it in your root/configuration.yaml
# If you use packages then created the folder inside packages/yourname/herethefolder and then a file for example light_kitchen.yaml
# Sub folder for configuration of sensor, groups, automations, scripts
# Example
# I recommend using subfolders it's better organized this way

# sensor: !include_dir_merge_list configuration/sensor/
# binary_sensor: !include_dir_merge_list configuration/binary_sensor/
# group: !include_dir_merge_named configuration/groups/  #You really need groups to use my theme :D
# automation: !include_dir_merge_list configuration/automations/
# script: !include_dir_merge_named configuration/scripts/
# switch: !include_dir_merge_list configuration/switch/

#Some more examples
# light: !include_dir_merge_list configuration/light/
# fan: !include_dir_merge_list configuration/fan/
# cover: !include_dir_merge_list configuration/cover/
# camera: !include_dir_merge_list configuration/camera/
# input_boolean: !include_dir_merge_named configuration/input_boolean/
# input_select: !include_dir_merge_named configuration/input_select/
# scene: !include configuration/scenes.yaml
