#dynamic_page:
  # addon:
  #   name: Hello dynamic page
  #   icon: fas:puzzle-piece
  #   path: 'dwains-theme/addons/dynamic_page/hello-dynamic-page/page.yaml'
  #   data:
  #     some_data: 'This is some data parsed.'
  #     some_other_data: 'and some other data.'